title: Black Ochre Data Labs
tagline: An Adelaide-based research group working on Indigenous Genomics
name: ""
cover: old_cover.jpg

url: https://tki-indigenous-genomics.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

remote_theme: zivong/jekyll-theme-hydure

plugins:
  - jekyll-remote-theme

social:
   github: tki-indigenous-genomics
