title: Black Ochre Data Labs
tagline: Indigenous Genomics research group located in Adelaide (co-funded by Telethon Kids Institute and Australian National University)

url: https://tki-indigenous-genomics.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

remote_theme: zivong/jekyll-theme-hydure

plugins:
  - jekyll-remote-theme

social:
   github: tki-indigenous-genomics
