title: Black Ochre Data Labs
tagline: An Adelaide-based research group working on Indigenous Genomics
name: "Black Ochre Data Labs"
cover: "https://github.com/tki-indigenous-genomics/tki-indigenous-genomics.github.io/blob/main/cover.jpg"

url: https://tki-indigenous-genomics.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

remote_theme: zivong/jekyll-theme-hydure

plugins:
  - jekyll-remote-theme

social:
   github: tki-indigenous-genomics
