title: Telethon Kids Institute - Indigenous Genomics
description: Indigenous Genomics research group located in Adelaide (co-funded by Australian National University)

url: https://tki-indigenous-genomics.github.io
baseurl: ""
remote_theme: zivong/jekyll-theme-hydure

plugins:
  - jekyll-remote-theme

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: CV
   url: /cv
 - title: Contact
   url: /contact

social:
   github: tki-indigenous-genomics
